"""Creación incial de tablas

Revision ID: 8117bfd3ede6
Revises: 9727b8558300
Create Date: 2025-10-10 23:06:12.706495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8117bfd3ede6'
down_revision = '9727b8558300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prueba_configuracion',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('tipo_prueba', sa.String(length=100), nullable=False),
    sa.Column('parametros_json', sa.Text(), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('tipo_prueba')
    )
    op.create_table('relacion_medico_paciente',
    sa.Column('relacion_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medico.medico_id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.paciente_id'], ),
    sa.PrimaryKeyConstraint('relacion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relacion_medico_paciente')
    op.drop_table('prueba_configuracion')
    # ### end Alembic commands ###
