"""Migración inicial de la base de datos

Revision ID: 9727b8558300
Revises: 
Create Date: 2025-10-10 16:29:58.722337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9727b8558300'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('consentimiento',
    sa.Column('consentimiento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_aceptacion', sa.DateTime(), nullable=True),
    sa.Column('politica_version', sa.String(length=50), nullable=True),
    sa.Column('permisos_otorgados', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('consentimiento_id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('medico',
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('centro_medico', sa.String(length=100), nullable=True),
    sa.Column('nro_colegiatura', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('medico_id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('paciente',
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.Column('fecha_diagnostico', sa.String(length=50), nullable=True),
    sa.Column('contacto_emergencia', sa.String(length=100), nullable=True),
    sa.Column('notas_medicas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('paciente_id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('resultado_prueba',
    sa.Column('resultado_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_prueba', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('nivel_riesgo', sa.String(length=50), nullable=True),
    sa.Column('confianza', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('archivo_referencia', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.paciente_id'], ),
    sa.PrimaryKeyConstraint('resultado_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado_prueba')
    op.drop_table('paciente')
    op.drop_table('medico')
    op.drop_table('consentimiento')
    op.drop_table('usuario')
    # ### end Alembic commands ###
